name: deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:

  # Собираем и пушим Docker-образ
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

        # Логинимся в Container registry
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        # Собираем и пушим Docker-образ
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: "${{ env.REGISTRY }}/${{ github.repository }}:${{ github.run_id }}"